keyword_extraction:
  model_name: "en_core_web_md"

document_extraction:
  max_docs: 50
  max_pages: 10
#  max_depth: 5
  redundancy_similarity_threshold: 0.9
  keyword_similarity_threshold: 0.5
  min_length_threshold: 50
  keyword_density_threshold: 0.05
  verbose: True

document_embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  model_kwargs:
    device: "cuda"                                                # "cuda", "cpu"
  encode_kwargs:
    normalize_embeddings: True

document_loader:
  chunk_size: 200
  chunk_overlap: 0

chatbot:
  llm_name: "llama-2-7b-chat.Q2_K.gguf"
  llm_params:
    temperature: 0.1
    max_tokens: 200
    top_p: 1
    n_gpu_layers: 40
    n_batch: 200
    n_ctx: 1000
    verbose: False
  chain_type: "stuff"                                           # "stuff", "map reduce", "refine", "map_rerank"
  retriever_params:
    search_kwargs:
      k: 1
  memory_params:
    memory_key: "chat_history"
    return_messages: True
    max_token_limit: 10
    output_key: "answer"
  return_source_documents: True
  return_generated_question: True
  verbose: False


